プリント文の追加
YuyaOba/SecondApp pull request #1
Opened 2020-11-13 10:30 UTC by YuyaOba

2020-11-13 11:02 UTC, khaki-ranger reviewed
コードレビューが出来ることが確認でしました！

2020-11-13 22:13 UTC, YuyaOba commented
CollectionViewを追加したのですが、'UICollectionView must be initialized with a non-nil layout parameter'とでて落ちます。

Flowlayoutがinit時に追加する必要があるようで38行目で追加しているのですが、ダメです…。

2020-11-13 22:31 UTC, khaki-ranger commented
> CollectionViewを追加したのですが、'UICollectionView must be initialized with a non-nil layout parameter'とでて落ちます。
> 
> Flowlayoutがinit時に追加する必要があるようで38行目で追加しているのですが、ダメです…。

コードレビューのリクエストを送ってください。

2020-11-13 22:57 UTC, khaki-ranger requested changes
```
view.addSubview(textField)
view.addSubview(discountCollectionView)
```

ViewController.swiftの47行目付近で2つのプロパティをaddSubviewしていますが、AutoLayoutの指定をしていないので、実行時エラーが発生すると思われます。

2020-11-14 01:30 UTC, YuyaOba commented
30行目に作成しているColecctionView内にAotLayoutして、addSubViewですよね？

2020-11-14 01:49 UTC, khaki-ranger requested changes
現状だと、ViewControllerクラスのtextFieldプロパティーとdiscountCollectionViewクラスは、addSubviewされているけど、AutoLayoutの指定がされていないと言うことです。

エラー文は読みましたか？

2020-11-14 02:07 UTC, khaki-ranger commented
> CollectionViewを追加したのですが、'UICollectionView must be initialized with a non-nil layout parameter'とでて落ちます。
> 
> Flowlayoutがinit時に追加する必要があるようで38行目で追加しているのですが、ダメです…。

_Flowlayoutがinit時に追加する必要がある_ 
この根拠は何ですか？

上記のエラー分の意味は分かっていますか？

2020-11-15 05:46 UTC, YuyaOba commented
直訳するとnil以外のパラメーターで初期化してくださいという意味だと思います。

2020-11-15 05:56 UTC, khaki-ranger commented
> 直訳するとnil以外のパラメーターで初期化してくださいという意味だと思います。

1. 主語は何ですか？
2. layoutの訳はどこに行ってしまったのでしょう？
3. このエラー分を読んで、どこに問題があると考えられますか？

2020-11-16 02:43 UTC, YuyaOba commented
1、UICollectionViewです
2、UICollectionViewは、nil以外のレイアウトパラメーターで初期化する必要があるという訳になるのではないでしょうか？
3、　overideした際にUICollectionViewにlayoutを指定する必要があると思います。

2020-11-16 02:51 UTC, khaki-ranger commented
> overideした際にUICollectionViewにlayoutを指定する必要がある

こう考える根拠がわからないのですが、どこからそう読み取れるのでしょうか？

2020-11-16 03:25 UTC, YuyaOba commented
少し整理してまた連絡します泣

2020-11-16 03:37 UTC, khaki-ranger commented
> 少し整理してまた連絡します泣

視点を変えて。今までできていたことなので、どこが違うのかを比較したらいいと思います。

2020-11-19 09:55 UTC, merged